# Local config changes for the JupyterLab container go here

ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER
# https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook

LABEL maintainer="Stephen Hepner <shepner@asyla.org>"
