# https://docs.docker.com/compose/compose-file/

services:
  ddclient:
    container_name: ddclient  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/ddclient:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
    - ./common.env
    - ./ddclient.env
    #environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #
    # https://docs.docker.com/compose/compose-file/#volumes
    volumes: /mnt/nas/data2/docker_01/ddclient/config:/config
    #ports:  # https://docs.docker.com/compose/compose-file/#ports
    #
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - ddclient_network
    #
    logging:  # https://docs.docker.com/compose/compose-file/#logging
      driver: syslog
      options:
        syslog-address: "tcp://10.0.0.73:514"
    #
    restart: unless-stopped
    #
    deploy:  # https://docs.docker.com/compose/compose-file/deploy/
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '.50'
          memory: 50M
          pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M

networks:
  ddclient_network:

