name: unifi-network-application

networks:
  unifi-network-application_net:


services:

  unifi-db:
    container_name: unifi-db
    # image: docker.io/mongo:3.6
    image: mongo:4.4.25-focal
    # user: ${PUID}:${PGID}
    user: 1003:1000
    environment:
      - PGID=1000
      - PUID=1003
      - TZ="America/Chicago"
    ports:
      - 27017:27017/tcp
    restart: unless-stopped
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ${INSTALL_FOLDER}/unifi/unifi-db:/data/db
    networks:
      - unifi-network-application_net

  unifi-network-application:
    container_name: unifi-network-application
    depends_on:
      unifi-db:
        condition: service_started
    environment:
      - MONGO_DBNAME=unifi-db
      - MONGO_HOST=unifi-db
      - MONGO_PASS=${DB_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_USER=unifi
      - PGID=1000
      - PUID=1003
      - TZ="America/Chicago"
    image: lscr.io/linuxserver/unifi-network-application:latest
    ports:
      - 1900:1900/udp # Required for 'Make controller discoverable on L2 network' option
      - 3478:3478/udp # Unifi STUN port
      - 5514:5514/udp # Remote syslog port
      - 6789:6789 # For mobile throughput test
      - 8080:8080 # Required for device communication
      - 8443:8443 # Unifi web admin, guest portal HTTPS redirect port
      - 8843:8843 # Unifi guest portal HTTPS redirect port
      - 8880:8880 # Unifi guest portal HTTP redirect port
      - 10001:10001/udp # Required for AP discovery
    restart: unless-stopped
    volumes:
      - ${INSTALL_FOLDER}/unifi/unifi-network-application:/config
    networks:
      - unifi-network-application_net

