# Traefik configuration [file](https://docs.traefik.io/providers/file/)

http:
  # web services that the container is publishing
  services:
    calibre_desktop:
      loadBalancer:
        servers:
          - url: http://calibre:8080
    calibre_web:
      loadBalancer:
        servers:
          - url: http://calibre:8081

  # how to present the original service
  routers:
    calibre_desktop:
      rule: Host(`calibre.asyla.org`)
      service: calibre_desktop
      entryPoints:
        - http
    calibre_web:
      rule: Host(`calibre.asyla.org`)
      service: calibre_web
      entryPoints:
        - calibre_web

tcp:
  services:
    calibre_rdp:
      loadBalancer:
        servers:
          - address: "calibre:3389"
  routers:
    calibre_rdp:
      rule: HostSNI(`*`) # must use wildcard for non-TLS services
      service: calibre_rdp
      entryPoints:
        - rdp

