# Traefik configuration [file](https://docs.traefik.io/providers/file/)

http:
  # Add the router
  routers:
    router0:
      rule: Host(`calibre.asyla.org`)
      service: calibre_desktop


  # Add the service
  services:
    calibre_desktop:
      loadBalancer:
        servers:
          - url: http://10.10.10.10:8080
