# https://docs.docker.com/compose/compose-file/

version: "3.9"

services:
  openssh-server:  # https://docs.linuxserver.io/images/docker-openssh-server
    container_name: openssh  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/openssh-server:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
      - ./common.env
    #  - ./syncthing.env
    environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
      - PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAy1Lm8RkHhF1gn+uL6li2hgVboxF2/PNoWWsugVowon56YLhf5jYjX61FzuNLgsm2oFvkJRDmR+dmdoJWgy52tByWiLuhGJjWUS/IMkrXN0Ookcg3ZTgwo+yg2n+SMe1jusazkoO6p4qXeVB18txlrj6zcwSrUxVhF8st04hHv93aNGl19G3U7NTzMVZnW+9Zkj9VvifbwEY4bKkeJtg4a/+8NtAnGB/q8JXiEWj/mbOS4KoGJu3Pv/kevSCkBJUPXJHfoW3Y5LvgO+yqpu6NoFca7Em1G8LctniNy6XctYSgP9afuWY3bxUpwCQayuRg02MCoiiFGBidrXr93uNkIw== shepner@ws01.asyla.org" #optional
      #- PUBLIC_KEY_FILE=/path/to/file #optional
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      #- PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=false #optional
      #- USER_PASSWORD=password #optional
      #- USER_PASSWORD_FILE=/path/to/file #optional
      #- USER_NAME=linuxserver.io #optional
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/openssh/config:/config
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 2222:2222
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - openssh_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

networks:
  syncthing_network:

