# https://docs.docker.com/compose/compose-file/

version: "3.9"

services:
  openssh-server:  # https://docs.linuxserver.io/images/docker-openssh-server
    container_name: openssh-server  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/openssh-server:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
      - ./common.env
    #  - ./openssh-server.env
    environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
      #- PUBLIC_KEY=string #optional
      #- PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_FILE=/config/shepner_rsa.pub
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      #- PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=false #optional
      #- USER_PASSWORD=password #optional
      #- USER_PASSWORD_FILE=/path/to/file #optional
      #- USER_NAME=linuxserver.io #optional
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/openssh-server/config:/config
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 2222:2222
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - openssh-server_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

networks:
  openssh-server_network:

