# https://docs.docker.com/compose/compose-file/

version: "3.9"

services:
  swag:  # https://docs.linuxserver.io/images/docker-swag
    container_name:swag  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/swag:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
      - ./common.env
    #  - ./openssh-server.env
    environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #  - URL=yourdomain.url
      - URL=${MY_DOMAIN}
    #  - VALIDATION=http
      - VALIDATION=dns
    #  - SUBDOMAINS=www, #optional
      - SUBDOMAINS=transmission
    #  - CERTPROVIDER= #optional
    #  - DNSPLUGIN=cloudflare #optional
      - DNSPLUGIN=cloudflare
    #  - PROPAGATION= #optional
    #  - DUCKDNSTOKEN= #optional
    #  - EMAIL= #optional
      - EMAIL=${MY_EMAIL}
    #  - ONLY_SUBDOMAINS=false #optional
      - ONLY_SUBDOMAINS=false
    #  - EXTRA_DOMAINS= #optional
    #  - STAGING=false #optional
      - STAGING=false
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/swag/config:/config
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 443:443
      - 80:80  #optional
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - swag_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

networks:
  swag_network:
  torrent_network:

