# https://docs.docker.com/compose/compose-file/

version: "3.9"

services:
  ddclient:
    container_name: syncthing  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/syncthing:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
      - ./common.env
    #  - ./syncthing.env
    #environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/syncthing/config:/config
      - /mnt/nas/data1/media/syncthing/data1:/data1  # inbound
      - /mnt/nas/data1/media/syncthing/data2:/data2  # outbound
      - /mnt/nas/data1/media/Videos:/Videos  # outbound: share the specific folders from here
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 8384:8384  # web interface
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - syncthing_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

networks:
  syncthing_network:

