# https://docs.docker.com/compose/compose-file/

version: "3.9"

services:

  # sonarr
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/sonarr:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
    - ./common.env
    #- ./ddclient.env
    #environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/sonarr/config:/config
      - /mnt/nas/data2/docker_01/transmission/downloads/complete:/downloads
      - /mnt/nas/data1/media/Videos:/tv
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 8989:8989
    #
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - torrent_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '4'
    #      memory: 50M
    #    reservations:
    #      cpus: '.25'
    #      memory: 20M

  # jackett
  # https://docs.linuxserver.io/images/docker-jackett
  jackett:
    container_name: jackett  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/jackett:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
    - ./common.env
    #- ./ddclient.env
    environment:  # https://docs.docker.com/compose/compose-file/#environment
      - AUTO_UPDATE=true   # optional
    #  - RUN_OPTS=<run options here> # optional
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/jackett/config:/config
      - /mnt/nas/data2/docker_01/jackett/downloads:/downloads
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 9117:9117
    #
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - torrent_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '2'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

  # transmission
  #https://docs.linuxserver.io/images/docker-transmission
  transmission:
    container_name: transmission  # https://docs.docker.com/compose/compose-file/#container_name
    #
    image: lscr.io/linuxserver/transmission:latest
    #
    env_file:  # https://docs.docker.com/compose/compose-file/#env_file
    - ./common.env
    #- ./ddclient.env
    #environment:  # https://docs.docker.com/compose/compose-file/#environment
    #  - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    #  - USER=username #optional
    #  - PASS=password #optional
    #  - WHITELIST=iplist #optional
    #  - PEERPORT=peerport #optional
    #  - HOST_WHITELIST=dnsname list #optional
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=Europe/London
    #
    volumes:  # https://docs.docker.com/compose/compose-file/#volumes
      - /mnt/nas/data2/docker_01/transmission/config:/config
      - /mnt/nas/data2/docker_01/transmission/watch:/watch
      - /mnt/nas/data2/docker_01/transmission/downloads:/downloads
    ports:  # https://docs.docker.com/compose/compose-file/#ports
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    #
    networks:  # https://docs.docker.com/compose/compose-file/#networks
      - torrent_network
    #
    restart: unless-stopped  # N/A for swarm
    #
    #deploy:  # https://docs.docker.com/compose/compose-file/deploy/
    #  mode: replicated
    #  replicas: 1
    #  resources:
    #    limits:
    #      cpus: '4'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M

