version: "3.8"

services:

  reverse-proxy:
    image: "traefik:v2.2"
    command: # use the `traefik.yml` instead
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # HTTP - general use
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # So that Traefik can listen to the Docker events
    
    #container_name: "traefik" # not used with Swarm
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_net:
    external: true
