version: "3.8"

services:
  traefik:
    image: "traefik:v2.2"
    ports:
      - "80:80"     # HTTP - general use
      - "443:443"   # HTTPS - general use
      - "8080:8080" # Traefik dashboard
      - "8081:8081" # Calibre web interface
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_net"
      - "--entrypoints.web.address=:80"
    deploy:
      placement:
        constraints:
          - node.role == manager
      

networks:
  traefik_net:
    external: true

