version: "3.8"

services:

  reverse-proxy:
    image: "traefik:v2.2"
    command: # use the `traefik.yml` instead
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_net"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # HTTP - general use
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_net:
    external: true
