http:
  routers:
    redirect-https:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      rule: hostregexp(`{any:.+}`)
      service: noop

  services:
    # noop service, the URL will be never called
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.0.1

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true


