## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  calibre_web_ep:
    address: ":8081"

providers:
  file: # [Traefik & File](https://docs.traefik.io/providers/file/)
    directory: "/config"
    watch: true
  docker: # [Traefik & Docker](https://docs.traefik.io/providers/docker/)
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

